In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import os.path as op
import pickle

In [2]:
A1=np.empty((0,5),dtype='float32')
U1=np.empty((0,7),dtype='float32')
node=['150','149','147','144','142','140','136','61']
mon=['Apr','Mar','Aug','Jun','Jul','Sep','May','Oct']
for j in node:
  for i in mon:
    inp= pd.read_csv('data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[1,2,3,15,16],low_memory=False)
    out= pd.read_csv('data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[5,6,7,8,17,18,19],low_memory=False)
    
    inp=np.array(inp,dtype='float32')
    out=np.array(out,dtype='float32')
    
    A1=np.append(A1, inp, axis=0)
    U1=np.append(U1, out, axis=0)

print(A1)
print(U1)


[[1.50000e+02 1.90401e+05 7.25000e+02 2.75500e+01 8.03900e+01]
 [1.50000e+02 1.90401e+05 8.25000e+02 2.75600e+01 8.03300e+01]
 [1.50000e+02 1.90401e+05 9.25000e+02 2.75800e+01 8.02400e+01]
 ...
 [6.10000e+01 1.91020e+05 1.94532e+05 2.93700e+01 7.52100e+01]
 [6.10000e+01 1.91020e+05 1.94632e+05 2.93500e+01 7.52700e+01]
 [6.10000e+01 1.91020e+05 1.94732e+05 2.93400e+01 7.53000e+01]]
[[ 28.     3.   -52.   ...  16.97  19.63  20.06]
 [ 28.    15.   -53.   ...  16.63  19.57  23.06]
 [ 31.    16.   -55.   ...  17.24  19.98  20.24]
 ...
 [ 76.    12.   -76.   ...   3.47   3.95   4.35]
 [ 75.    13.   -76.   ...   3.88   4.33   4.42]
 [ 76.    12.   -75.   ...   3.46   4.07   4.28]]


In [3]:
from sklearn.preprocessing import MinMaxScaler
import warnings
scaler_obj=MinMaxScaler()
X1=scaler_obj.fit_transform(A1)
Y1=scaler_obj.fit_transform(U1)

warnings.filterwarnings(action='ignore', category=UserWarning)

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.25,random_state=0)

In [8]:
import pickle
loaded_model_fit7 = pickle.load(open("Models_File/xgboost.sav", 'rb'))
y_test_pred=loaded_model_fit7.predict(x_test)
y_test_pred

array([[0.0001119 , 0.06553669, 0.0001257 , ..., 0.00280868, 0.0019619 ,
        0.00078863],
       [0.00011277, 0.06553669, 0.00011924, ..., 0.01744912, 0.01196927,
        0.00398226],
       [0.0001118 , 0.06553669, 0.00011916, ..., 0.02884349, 0.01745062,
        0.00599684],
       ...,
       [0.00011255, 0.06553669, 0.00011596, ..., 0.02273857, 0.01367347,
        0.00507223],
       [0.00011255, 0.06553669, 0.00012076, ..., 0.03629657, 0.02667749,
        0.00794878],
       [0.00011293, 0.06553669, 0.00011924, ..., 0.00797539, 0.00537983,
        0.0037    ]], dtype=float32)

In [10]:
from numpy import savetxt
savetxt('ARRAY_DATA/xgboost_y_test_pred.csv', y_test_pred[:1001], delimiter=',')

In [16]:
from numpy import loadtxt
data = loadtxt('ARRAY_DATA/knn_y_test.csv', delimiter=',')
data

array([[0.00010812, 0.06553657, 0.0001368 , ..., 0.00465421, 0.0032433 ,
        0.00139601],
       [0.00011141, 0.06553698, 0.0001189 , ..., 0.00947999, 0.00574444,
        0.00183423],
       [0.00011193, 0.0655366 , 0.0001198 , ..., 0.03056333, 0.01916761,
        0.00634215],
       ...,
       [0.0001126 , 0.06553672, 0.00011279, ..., 0.01996804, 0.01252907,
        0.00401423],
       [0.00011253, 0.06553655, 0.00012397, ..., 0.03575373, 0.02222976,
        0.00729255],
       [0.000112  , 0.06553673, 0.00011786, ..., 0.00466493, 0.00372249,
        0.0052013 ]])