In [3]:
import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [4]:
A1=np.empty((0,5),dtype='float32')
U1=np.empty((0,7),dtype='float32')
node=['150','149','147','144','142','140','136','61']
mon=['Apr','Mar','Aug','Jun','Jul','Sep','May','Oct']
for j in node:
  for i in mon:
    inp= pd.read_csv('../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[1,2,3,15,16],low_memory=False)
    out= pd.read_csv('../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[5,6,7,8,17,18,19],low_memory=False)
    
    inp=np.array(inp,dtype='float32')
    out=np.array(out,dtype='float32')
    
    A1=np.append(A1, inp, axis=0)
    U1=np.append(U1, out, axis=0)

print(A1)
print(U1)


[[1.50000e+02 1.90401e+05 7.25000e+02 2.75500e+01 8.03900e+01]
 [1.50000e+02 1.90401e+05 8.25000e+02 2.75600e+01 8.03300e+01]
 [1.50000e+02 1.90401e+05 9.25000e+02 2.75800e+01 8.02400e+01]
 ...
 [6.10000e+01 1.91020e+05 1.94532e+05 2.93700e+01 7.52100e+01]
 [6.10000e+01 1.91020e+05 1.94632e+05 2.93500e+01 7.52700e+01]
 [6.10000e+01 1.91020e+05 1.94732e+05 2.93400e+01 7.53000e+01]]
[[ 28.     3.   -52.   ...  16.97  19.63  20.06]
 [ 28.    15.   -53.   ...  16.63  19.57  23.06]
 [ 31.    16.   -55.   ...  17.24  19.98  20.24]
 ...
 [ 76.    12.   -76.   ...   3.47   3.95   4.35]
 [ 75.    13.   -76.   ...   3.88   4.33   4.42]
 [ 76.    12.   -75.   ...   3.46   4.07   4.28]]


In [1]:
from PyEMD import EMD

In [10]:
from sklearn.decomposition import PCA
temp=np.array([2,3])
obj1=PCA()
X1=obj1.fit_transform(A1)
X1

array([[-1.1033539e+05, -3.3105413e+03,  2.0052944e+01,  2.5551056e+01,
        -3.7359259e+00],
       [-1.1023628e+05, -3.3114587e+03,  2.0054895e+01,  2.5477852e+01,
        -3.7355926e+00],
       [-1.1013157e+05, -3.3113188e+03,  2.0054281e+01,  2.5372395e+01,
        -3.7327182e+00],
       ...,
       [ 8.3470836e+04, -2.6687417e+03, -6.4515213e+01, -2.1583786e+00,
         4.8166686e-01],
       [ 8.3570844e+04, -2.6687297e+03, -6.4510780e+01, -2.1087511e+00,
         4.7501981e-01],
       [ 8.3670836e+04, -2.6687175e+03, -6.4507385e+01, -2.0904481e+00,
         4.7251290e-01]], dtype=float32)

In [12]:
A1

array([[1.50000e+02, 1.90401e+05, 7.25000e+02, 2.75500e+01, 8.03900e+01],
       [1.50000e+02, 1.90401e+05, 8.25000e+02, 2.75600e+01, 8.03300e+01],
       [1.50000e+02, 1.90401e+05, 9.25000e+02, 2.75800e+01, 8.02400e+01],
       ...,
       [6.10000e+01, 1.91020e+05, 1.94532e+05, 2.93700e+01, 7.52100e+01],
       [6.10000e+01, 1.91020e+05, 1.94632e+05, 2.93500e+01, 7.52700e+01],
       [6.10000e+01, 1.91020e+05, 1.94732e+05, 2.93400e+01, 7.53000e+01]],
      dtype=float32)

In [11]:
inv=obj1.inverse_transform(X1)
inv

array([[1.4999826e+02, 1.9040183e+05, 7.2568750e+02, 2.7549892e+01,
        8.0389305e+01],
       [1.4999991e+02, 1.9040091e+05, 8.2479688e+02, 2.7560049e+01,
        8.0329895e+01],
       [1.4999991e+02, 1.9040103e+05, 9.2950781e+02, 2.7578588e+01,
        8.0239922e+01],
       ...,
       [6.1000145e+01, 1.9101998e+05, 1.9453203e+05, 2.9370026e+01,
        7.5209755e+01],
       [6.1000145e+01, 1.9101998e+05, 1.9463205e+05, 2.9350023e+01,
        7.5269760e+01],
       [6.1000145e+01, 1.9101998e+05, 1.9473203e+05, 2.9340023e+01,
        7.5299759e+01]], dtype=float32)