In [8]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import os.path as op
from csv import writer
import math
import cmath
import pickle

In [9]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Model,Sequential,load_model
from keras.layers import Input, Embedding
from keras.layers import Dense, Bidirectional
from keras.layers.recurrent import LSTM
import keras.metrics as metrics
import itertools
from tensorflow.python.keras.utils.data_utils import Sequence
from decimal import Decimal
from keras.layers import Conv1D,MaxPooling1D,Flatten,Dense

In [10]:
A1=np.empty((0,5),dtype='float32')
U1=np.empty((0,7),dtype='float32')
node=['150','149','147','144','142','140','136','61']
mon=['Apr','Mar','Aug','Jun','Jul','Sep','May','Oct']
for j in node:
  for i in mon:
    inp= pd.read_csv('../../../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[1,2,3,15,16])
    out= pd.read_csv('../../../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[5,6,7,8,17,18,19])
    
    inp=np.array(inp,dtype='float32')
    out=np.array(out,dtype='float32')
    
    A1=np.append(A1, inp, axis=0)
    U1=np.append(U1, out, axis=0)

print(A1)
print(U1)

[[1.50000e+02 1.90401e+05 7.25000e+02 2.75500e+01 8.03900e+01]
 [1.50000e+02 1.90401e+05 8.25000e+02 2.75600e+01 8.03300e+01]
 [1.50000e+02 1.90401e+05 9.25000e+02 2.75800e+01 8.02400e+01]
 ...
 [6.10000e+01 1.91020e+05 1.94532e+05 2.93700e+01 7.52100e+01]
 [6.10000e+01 1.91020e+05 1.94632e+05 2.93500e+01 7.52700e+01]
 [6.10000e+01 1.91020e+05 1.94732e+05 2.93400e+01 7.53000e+01]]
[[ 28.     3.   -52.   ...  16.97  19.63  20.06]
 [ 28.    15.   -53.   ...  16.63  19.57  23.06]
 [ 31.    16.   -55.   ...  17.24  19.98  20.24]
 ...
 [ 76.    12.   -76.   ...   3.47   3.95   4.35]
 [ 75.    13.   -76.   ...   3.88   4.33   4.42]
 [ 76.    12.   -75.   ...   3.46   4.07   4.28]]


In [15]:
from sklearn.decomposition import PCA
import warnings
scaler_obj1=PCA(svd_solver='full')
scaler_obj2=PCA(svd_solver='full')
X1=scaler_obj1.fit_transform(A1)
Y1=scaler_obj2.fit_transform(U1)

warnings.filterwarnings(action='ignore', category=UserWarning)

X1=X1[:,np.newaxis,:]
Y1=Y1[:,np.newaxis,:]

In [16]:
from keras import backend as K
def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1))

In [17]:
model = Sequential()
model.add(keras.Input(shape=(1,5)))
model.add(tf.keras.layers.GRU(14,activation="tanh",use_bias=True,kernel_initializer="glorot_uniform",bias_initializer="zeros", 
                                kernel_regularizer=keras.regularizers.l1_l2(l1=1e-5, l2=1e-4),
                                bias_regularizer=keras.regularizers.l2(1e-4),
                                activity_regularizer=keras.regularizers.l2(1e-5)))
model.add(keras.layers.Dropout(.1))
model.add(Dense(7))
model.add(keras.layers.BatchNormalization(axis=-1,momentum=0.99,epsilon=0.001,center=True,scale=True,
                                beta_initializer="zeros",gamma_initializer="ones",
                                moving_mean_initializer="zeros",moving_variance_initializer="ones",trainable=True))
model.add(keras.layers.ReLU())
model.compile(optimizer=keras.optimizers.Adam(learning_rate=1e-5),loss='mse',metrics=['accuracy','mse','mae',rmse])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_1 (GRU)                 (None, 14)                882       
                                                                 
 dropout_1 (Dropout)         (None, 14)                0         
                                                                 
 dense_1 (Dense)             (None, 7)                 105       
                                                                 
 batch_normalization_1 (Batc  (None, 7)                28        
 hNormalization)                                                 
                                                                 
 re_lu_1 (ReLU)              (None, 7)                 0         
                                                                 
Total params: 1,015
Trainable params: 1,001
Non-trainable params: 14
___________________________________________________

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X1, Y1, test_size=0.25, random_state=42)

history2 = model.fit(x_train,y_train,batch_size=256,epochs=50, validation_split=0.1)

Epoch 1/50
4563/4563 [==============================] - 55s 12ms/step - loss: 2296374272.0000 - accuracy: 0.1494 - mse: 2296471552.0000 - mae: 96.6970 - rmse: 197.0939 - val_loss: 30779.7090 - val_accuracy: 0.1411 - val_mse: 30779.7461 - val_mae: 72.9065 - val_rmse: 137.4894
Epoch 2/50
4563/4563 [==============================] - 53s 12ms/step - loss: 2296356864.0000 - accuracy: 0.1428 - mse: 2296454144.0000 - mae: 96.6854 - rmse: 197.0893 - val_loss: 30778.8359 - val_accuracy: 0.1396 - val_mse: 30778.8770 - val_mae: 72.8932 - val_rmse: 137.4845
Epoch 3/50
4563/4563 [==============================] - 54s 12ms/step - loss: 2296363264.0000 - accuracy: 0.1472 - mse: 2296460544.0000 - mae: 96.6758 - rmse: 197.0874 - val_loss: 30778.1562 - val_accuracy: 0.1602 - val_mse: 30778.1973 - val_mae: 72.8822 - val_rmse: 137.4800
Epoch 4/50
4563/4563 [==============================] - 53s 12ms/step - loss: 2296357632.0000 - accuracy: 0.1589 - mse: 2296455168.0000 - mae: 96.6666 - rmse: 197.0860 - va

Epoch 31/50
4563/4563 [==============================] - 53s 12ms/step - loss: 2296374528.0000 - accuracy: 0.1705 - mse: 2296471808.0000 - mae: 96.6057 - rmse: 197.0713 - val_loss: 30776.9941 - val_accuracy: 0.1473 - val_mse: 30777.0371 - val_mae: 72.8306 - val_rmse: 137.4686
Epoch 32/50
4563/4563 [==============================] - 53s 12ms/step - loss: 2296372480.0000 - accuracy: 0.1707 - mse: 2296469760.0000 - mae: 96.6051 - rmse: 197.0704 - val_loss: 30777.0137 - val_accuracy: 0.1469 - val_mse: 30777.0527 - val_mae: 72.8308 - val_rmse: 137.4686
Epoch 33/50
4563/4563 [==============================] - 53s 12ms/step - loss: 2296357120.0000 - accuracy: 0.1717 - mse: 2296454400.0000 - mae: 96.6035 - rmse: 197.0668 - val_loss: 30776.9824 - val_accuracy: 0.1472 - val_mse: 30777.0254 - val_mae: 72.8304 - val_rmse: 137.4683
Epoch 34/50
4563/4563 [==============================] - 54s 12ms/step - loss: 2296357376.0000 - accuracy: 0.1719 - mse: 2296454656.0000 - mae: 96.6044 - rmse: 197.0705 

In [20]:
model.evaluate(x_test,y_test)

13518/13518 [==============================] - 180s 13ms/step - loss: 1432071.7500 - accuracy: 0.1475 - mse: 1432085.3750 - mae: 74.2265 - rmse: 141.0122


[1432071.75,
 0.1475204974412918,
 1432085.375,
 74.22654724121094,
 141.01223754882812]

In [21]:
model.evaluate(x_train,y_train)

40554/40554 [==============================] - 537s 13ms/step - loss: 2066725120.0000 - accuracy: 0.1478 - mse: 2066737920.0000 - mae: 94.2109 - rmse: 191.0949


[2066725120.0,
 0.14784526824951172,
 2066737920.0,
 94.21088409423828,
 191.09494018554688]

In [22]:
df1=pd.DataFrame(history2.history['loss'],columns=["Loss"])
df1=df1.join(pd.DataFrame(history2.history["val_loss"],columns=["Val Loss"]))
df1=df1.join(pd.DataFrame(history2.history["accuracy"],columns=['Accuracy']))
df1=df1.join(pd.DataFrame(history2.history["val_accuracy"],columns=['Val Accuracy']))
df1=df1.join(pd.DataFrame(history2.history["mse"],columns=['MSE']))
df1=df1.join(pd.DataFrame(history2.history["val_mse"],columns=['Val MSE']))
df1=df1.join(pd.DataFrame(history2.history["mae"],columns=['MAE']))
df1=df1.join(pd.DataFrame(history2.history["val_mae"],columns=['Val MAE']))
df1=df1.join(pd.DataFrame(history2.history["rmse"],columns=['RMSE']))
df1=df1.join(pd.DataFrame(history2.history["val_mse"],columns=['Val RMSE']))
df1

Loss      Val Loss  Accuracy  Val Accuracy           MSE  \
0   2.296374e+09  30779.708984  0.149436      0.141140  2.296472e+09   
1   2.296357e+09  30778.835938  0.142781      0.139645  2.296454e+09   
2   2.296363e+09  30778.156250  0.147191      0.160157  2.296461e+09   
3   2.296358e+09  30778.187500  0.158868      0.158688  2.296455e+09   
4   2.296365e+09  30778.277344  0.164639      0.158617  2.296462e+09   
5   2.296347e+09  30778.253906  0.169908      0.158565  2.296444e+09   
6   2.296356e+09  30778.177734  0.174336      0.160683  2.296453e+09   
7   2.296358e+09  30777.537109  0.176364      0.162410  2.296455e+09   
8   2.296348e+09  30777.650391  0.177316      0.162228  2.296446e+09   
9   2.296367e+09  30777.476562  0.177832      0.162489  2.296465e+09   
10  2.296356e+09  30777.451172  0.177356      0.162633  2.296453e+09   
11  2.296355e+09  30777.382812  0.177461      0.163204  2.296452e+09   
12  2.296346e+09  30777.273438  0.177128      0.163596  2.296443e+09   
13  2.296365e+09  30777.251953  0.175482      0.163562  2.296462e+09   
14  2.296351e+09  30777.822266  0.176612      0.149809  2.296449e+09   
15  2.296355e+09  30777.351562  0.182871      0.160271  2.296452e+09   
16  2.296349e+09  30777.544922  0.180499      0.151274  2.296446e+09   
17  2.296368e+09  30777.351562  0.178547      0.149228  2.296465e+09   
18  2.296351e+09  30777.503906  0.177987      0.149017  2.296449e+09   
19  2.296365e+09  30777.332031  0.177478      0.149847  2.296462e+09   
20  2.296375e+09  30777.160156  0.176519      0.150933  2.296472e+09   
21  2.296363e+09  30777.222656  0.176403      0.150471  2.296460e+09   
22  2.296371e+09  30777.164062  0.177125      0.151148  2.296469e+09   
23  2.296353e+09  30777.320312  0.176034      0.151460  2.296451e+09   
24  2.296348e+09  30777.156250  0.176557      0.159734  2.296445e+09   
25  2.296350e+09  30777.296875  0.176528      0.151636  2.296447e+09   
26  2.296344e+09  30777.179688  0.174128      0.147673  2.296441e+09   
27  2.296368e+09  30777.140625  0.174199      0.147219  2.296465e+09   
28  2.296355e+09  30777.156250  0.174125      0.147155  2.296453e+09   
29  2.296366e+09  30777.121094  0.170882      0.147025  2.296463e+09   
30  2.296375e+09  30776.994141  0.170495      0.147326  2.296472e+09   
31  2.296372e+09  30777.013672  0.170666      0.146924  2.296470e+09   
32  2.296357e+09  30776.982422  0.171694      0.147210  2.296454e+09   
33  2.296357e+09  30777.031250  0.171921      0.146855  2.296455e+09   
34  2.296367e+09  30777.021484  0.170757      0.148988  2.296465e+09   
35  2.296372e+09  30777.041016  0.170506      0.147579  2.296469e+09   
36  2.296364e+09  30777.189453  0.172195      0.147131  2.296461e+09   
37  2.296345e+09  30777.072266  0.171271      0.147568  2.296443e+09   
38  2.296361e+09  30777.056641  0.171495      0.147182  2.296458e+09   
39  2.296347e+09  30776.929688  0.170825      0.146758  2.296444e+09   
40  2.296367e+09  30776.927734  0.171991      0.147796  2.296465e+09   
41  2.296349e+09  30776.998047  0.172483      0.148744  2.296446e+09   
42  2.296366e+09  30776.820312  0.172047      0.148636  2.296464e+09   
43  2.296368e+09  30776.984375  0.170218      0.147452  2.296465e+09   
44  2.296358e+09  30776.917969  0.170678      0.150845  2.296455e+09   
45  2.296364e+09  30776.853516  0.171039      0.151724  2.296461e+09   
46  2.296356e+09  30776.855469  0.171806      0.150664  2.296453e+09   
47  2.296349e+09  30776.742188  0.170671      0.149169  2.296446e+09   
48  2.296356e+09  30776.802734  0.170320      0.149390  2.296454e+09   
49  2.296354e+09  30776.880859  0.169480      0.149210  2.296451e+09   

         Val MSE        MAE    Val MAE        RMSE      Val RMSE  
0   30779.746094  96.697021  72.906517  197.093933  30779.746094  
1   30778.876953  96.685364  72.893196  197.089279  30778.876953  
2   30778.197266  96.675766  72.882217  197.087402  30778.197266  
3   30778.228516  96.666580  72.872559  197.086044  30778.228516  
4   

In [23]:
df1.to_excel("GRU_tanh_mse.xlsx")

In [25]:
model_json = model.to_json()
with open("gru_tanh_mse.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("gru_tanh_mse.h5")
print("Saved model to disk")

Saved model to disk


In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X1, Y1, test_size=0.25, random_state=42)

from keras.models import model_from_json
json_file = open('gru_tanh_mse.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("gru_tanh_mse.h5")
print("Loaded model from disk")
loaded_model.compile(optimizer=keras.optimizers.Adam(learning_rate=1e-5),loss='mse',metrics=['accuracy','mse','mae',rmse])
print(loaded_model.evaluate(x_train, y_train, verbose=0))

Loaded model from disk
[2066725120.0, 0.14784526824951172, 2066737920.0, 94.21088409423828, 191.09494018554688]


In [27]:
print(loaded_model.evaluate(x_test,y_test))

13518/13518 [==============================] - 100s 7ms/step - loss: 1432071.7500 - accuracy: 0.1475 - mse: 1432085.3750 - mae: 74.2265 - rmse: 141.0122
[1432071.75, 0.1475204974412918, 1432085.375, 74.22654724121094, 141.01223754882812]


In [28]:
print(loaded_model.evaluate(x_train,y_train))

40554/40554 [==============================] - 299s 7ms/step - loss: 2066725120.0000 - accuracy: 0.1478 - mse: 2066737920.0000 - mae: 94.2109 - rmse: 191.0949
[2066725120.0, 0.14784526824951172, 2066737920.0, 94.21088409423828, 191.09494018554688]


In [ ]:
plt.plot(history2.history['loss'])
plt.plot(history2.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')

plt.show()

plt.plot(history2.history['accuracy'])
plt.plot(history2.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X1, Y1, test_size=0.25, random_state=42)

y_test_pred=model.predict(x_test)
y_test_pred

In [ ]:
y_test

In [ ]:
y_test=y_test[:,0]

In [ ]:
from numpy import savetxt
savetxt('gru_tanh_mse_y_test_pred.csv', y_test_pred[:1001], delimiter=',')

In [ ]:
from numpy import savetxt
savetxt('gru_tanh_mse_y_test.csv', y_test[:1001], delimiter=',')

In [ ]:
#completed