# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import os.path as op
import pickle

# Data Fetching

In [3]:
A1=np.empty((0,5),dtype='float32')
U1=np.empty((0,7),dtype='float32')
node=['150','149','147','144','142','140','136','61']
mon=['Apr','Mar','Aug','Jun','Jul','Sep','May','Oct']
for j in node:
  for i in mon:
    inp= pd.read_csv('../../../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[1,2,3,15,16],low_memory=False)
    out= pd.read_csv('../../../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[5,6,7,8,17,18,19],low_memory=False)
    
    inp=np.array(inp,dtype='float32')
    out=np.array(out,dtype='float32')
    
    A1=np.append(A1, inp, axis=0)
    U1=np.append(U1, out, axis=0)

print(A1)
print(U1)


[[1.50000e+02 1.90401e+05 7.25000e+02 2.75500e+01 8.03900e+01]
 [1.50000e+02 1.90401e+05 8.25000e+02 2.75600e+01 8.03300e+01]
 [1.50000e+02 1.90401e+05 9.25000e+02 2.75800e+01 8.02400e+01]
 ...
 [6.10000e+01 1.91020e+05 1.94532e+05 2.93700e+01 7.52100e+01]
 [6.10000e+01 1.91020e+05 1.94632e+05 2.93500e+01 7.52700e+01]
 [6.10000e+01 1.91020e+05 1.94732e+05 2.93400e+01 7.53000e+01]]
[[ 28.     3.   -52.   ...  16.97  19.63  20.06]
 [ 28.    15.   -53.   ...  16.63  19.57  23.06]
 [ 31.    16.   -55.   ...  17.24  19.98  20.24]
 ...
 [ 76.    12.   -76.   ...   3.47   3.95   4.35]
 [ 75.    13.   -76.   ...   3.88   4.33   4.42]
 [ 76.    12.   -75.   ...   3.46   4.07   4.28]]


# Principal component analysis Decomposition

In [4]:
from sklearn.decomposition import PCA
import warnings
scaler_obj1=PCA()
scaler_obj2=PCA()
X1=scaler_obj1.fit_transform(A1)
Y1=scaler_obj2.fit_transform(U1)

warnings.filterwarnings(action='ignore', category=UserWarning)

# Parameter Tuning

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import RandomizedSearchCV

def hyperParameterTuning(X_train, y_train):
    param_tuning = {
        'learning_rate': [0.01, 0.1],
        'max_depth': [7,8,10,],
        'min_child_weight': [1, 3, 5],
        'subsample': [0.5, 0.7],
        'n_estimators' : [80,90,100,200,400,1000],
        'objective': ['reg:squarederror','count:poisson']
    }

    xgb_model = XGBRegressor(tree_method='gpu_hist', gpu_id=0)

    gsearch = RandomizedSearchCV(estimator = xgb_model, param_distributions = param_tuning, n_iter = 5, cv = 2, verbose=2, random_state=0, n_jobs = -1)

    
    grid_result = MultiOutputRegressor(gsearch).fit(x_train, y_train)

    return grid_result.estimators_[0].best_params_

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.25,random_state=0)

params=hyperParameterTuning(x_train,y_train)
params

# Model

In [6]:
# Splitting Data into training and testing dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.25,random_state=42)

from sklearn.multioutput import MultiOutputRegressor
from xgboost import XGBRegressor

#creating object of sgboostregressor
model1=MultiOutputRegressor(XGBRegressor(tree_method='gpu_hist', gpu_id=0,max_depth=8,cosample_bytree=.5,learning_rate=.1,min_child_weight=3,
                   n_estimators=200,subsample=.7))

#training the model
model_fit1=model1.fit(x_train, y_train)
print("Model training is Done!!")

#saving as file
filename1 = 'xgboost.sav'
pickle.dump(model_fit1, open(filename1, 'wb'))

[13:21:24] WARNING: ../src/learner.cc:576: 
Parameters: { "cosample_bytree" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




KeyboardInterrupt: 

# Error Analysis

In [118]:
from sklearn.metrics import r2_score
from sklearn import metrics
train_sizes=['NO2','O3','NO','CO','PM1','PM2.5','PM10']

#finding out the r2 score
y_train_pred1=model1.predict(x_train)
r2_train1=r2_score(y_train,y_train_pred1,multioutput='variance_weighted')

y_test_pred1=model1.predict(x_test)
r2_test1=r2_score(y_test,y_test_pred1,multioutput='variance_weighted')

print('r2 score on train data '+str(r2_train1))
print('r2 score on test data '+ str(r2_test1))

xgboost_mae=metrics.mean_absolute_error(y_test, y_test_pred1)
xgboost_mse=metrics.mean_squared_error(y_test, y_test_pred1)
xgboost_rmse=np.sqrt(xgboost_mse)
print('Mean Absolute Error:',xgboost_mae)
print('Mean Squared Error:',xgboost_mse )
print('Root Mean Squared Error:',xgboost_rmse)
print(' \n')

r2 score on train data 0.9315455074103038
r2 score on test data 0.9310061554157045
Mean Absolute Error: 0.0008703509
Mean Squared Error: 9.53231e-06
Root Mean Squared Error: 0.003087444
 



# Prediction of particles

In [10]:
import pickle
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.25,random_state=42)
loaded_model_fit7 = pickle.load(open("xgboost.sav", 'rb'))
y_test_pred=loaded_model_fit7.predict(x_test)
print("Predicted :\n",y_test_pred)
print("\n")
r2_test=r2_score(y_test,y_test_pred,multioutput='variance_weighted')
print("R2 Score : ",r2_test)

/home/utkarsh/.local/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


[11:02:14] WARNING: ../src/gbm/gbtree.cc:386: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[11:02:14] WARNING: ../src/learner.cc:223: No visible GPU is found, setting `gpu_id` to -1
[11:02:14] WARNING: ../src/gbm/gbtree.cc:386: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[11:02:14] WARNING: ../src/learner.cc:223: No visible GPU is found, setting `gpu_id` to -1
[11:02:14] WARNING: ../src/gbm/gbtree.cc:386: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[11:02:14] WARNING: ../src/learner.cc:223: No visible GPU is found, setting `gpu_id` to -1
[11:02:14] WARNING: ../src/gbm/gbtree.cc:386: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
[11:02:14] WARNING: ../src/learner.cc:223: No visible GPU is found, setting `gpu_id` to -1
[11:02:14] WARNING: ../src/gbm/gbtree.cc:386: Loading from a raw memory buffer on CPU only machine.  Changing tr

In [11]:
x_test=scaler_obj1.inverse_transform(x_test)
y_test_pred=scaler_obj2.inverse_transform(y_test_pred)
y_test=scaler_obj2.inverse_transform(y_test)
pd.DataFrame(y_test_pred)

0        1          2           3          4          5  \
0       47.849255  11.8641 -80.664482  490.139801   2.968223   3.418961   
1       31.278259  11.8641  -5.546434  341.499512  10.155688  10.203463   
2       51.198467  11.8641 -25.094217 -132.613449  13.112359  15.961463   
3       49.207836  11.8641 -44.744858  681.868164  29.937065  35.181923   
4       33.853252  11.8641  -5.958789  -82.559654   6.641768   8.177238   
...           ...      ...        ...         ...        ...        ...   
432566  34.035519  11.8641   4.500061   -2.882016   6.573976   8.000960   
432567  50.424248  11.8641 -70.336044  446.676208   1.701109   2.388438   
432568  46.449802  11.8641 -32.155125   42.305916  46.402546  53.961266   
432569  50.424248  11.8641 -72.692688  788.745911   0.973941  -1.853863   
432570  31.278259  11.8641 -40.294590  743.140747   3.909797   5.449862   

                6  
0        3.777236  
1       13.379510  
2       18.418491  
3       34.957455  
4       11.174068  
...           ...  
432566   9.871785  
432567   3.165210  
432568  59.906017  
432569   2.013185  
432570   9.473277  

[432571 rows x 7 columns]

In [12]:
import datetime
from datetime import datetime
temp_arr=x_test[0:,1]
dates=list()
for i in range(0,len(temp_arr)):
    datetime_str=str(int(temp_arr[i]))
    datetime_str=datetime_str[0:6]
    if(datetime_str[4:6]=="00"):
        datetime_str=datetime_str[0:4]+'1'
    datetime_obj = datetime.strptime(datetime_str,"%y%m%d")
    dates.append(str(datetime_obj.date()))


In [56]:
import pandas as pd
df1=pd.DataFrame(y_test,index=dates,columns=['NO2','O3','NO','CO','PM1','PM2.5','PM10'])
df1.index.name="DATE"
print("Actual Values:")
df1

Actual Values:


NO2          O3         NO           CO    PM1  PM2.5  \
DATE                                                                      
2019-06-04  81.999992   35.592297 -78.999992   705.999939   2.00   2.42   
2019-09-26  19.000019   49.613506  -7.999984   478.000000  10.17  10.95   
2019-05-14  58.000042   37.749409 -34.000019  -107.000000  27.40  31.75   
2019-04-18  82.999977    5.392773 -26.999977  1579.999878  39.41  45.18   
2019-08-31   5.000026   53.927723  -4.000016  -169.999985   6.90   8.25   
...               ...         ...        ...          ...    ...    ...   
2019-03-29  -2.999957  103.541229  63.999969    28.999987   7.13   7.98   
2019-06-29  76.999962   39.906517 -81.000031   412.999969   1.94   2.61   
2019-10-02  20.999990    3.235663 -48.000000    -3.000041  52.91  61.52   
2019-09-15  70.999954   39.906517 -86.999977   607.999878   7.60   8.02   
2019-07-09  -8.999969   -5.392773 -16.000017   592.000000   3.50   4.22   

                 PM10  
DATE                   
2019-06-04   2.820000  
2019-09-26  12.670000  
2019-05-14  41.180000  
2019-04-18  50.160000  
2019-08-31   9.110000  
...               ...  
2019-03-29   8.190000  
2019-06-29   4.120000  
2019-10-02  67.230003  
2019-09-15   8.020000  
2019-07-09   4.390000  

[432571 rows x 7 columns]

In [57]:
arr=["Y_Actual"]*25
temp_df1=df1.head(25)
temp_df1['Data']=arr
temp_df1.to_excel("xgboost_y_test.xlsx")
temp_df1

/tmp/ipykernel_2698415/2545994415.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df1['Data']=arr


NO2         O3          NO           CO        PM1  \
DATE                                                                   
2019-06-04  81.999992  35.592297  -78.999992   705.999939   2.000000   
2019-09-26  19.000019  49.613506   -7.999984   478.000000  10.170000   
2019-05-14  58.000042  37.749409  -34.000019  -107.000000  27.400000   
2019-04-18  82.999977   5.392773  -26.999977  1579.999878  39.410000   
2019-08-31   5.000026  53.927723   -4.000016  -169.999985   6.900000   
2019-06-29   9.999954  34.513744   35.000008    51.999977   6.890000   
2019-07-28  24.000046   6.471327  -37.999985   -68.999977  18.180000   
2019-07-09  72.000038  11.864100  -93.000031   649.000000   3.120000   
2019-09-07  52.000031  65.791824  -72.999992   243.999969  20.639999   
2019-07-17   7.999982  50.692062   -2.999976   206.000031   4.890000   
2019-08-26  67.000015   5.392773  -34.000019   904.000000  24.240000   
2019-06-02  42.999966  -8.628436    1.999984   302.999939  77.669998   
2019-07-31  81.999992  36.670853  -96.999992   615.000000   4.780000   
2019-07-02  19.000019  -5.392773  -42.999992  -153.999969  19.459999   
2019-08-10  53.000019  -3.235663  -54.999992   831.999939  41.430000   
2019-03-14  74.000008  29.120972 -100.000023   479.000000   1.240000   
2019-09-21   4.000040  87.362915   -6.999992   253.000000  75.269997   
2019-09-14  26.000015  20.492535 -142.000015   321.000000  48.099998   
2019-05-16  20.999990  60.399052 -151.000000    26.000032   8.720000   
2019-09-23  21.999977  33.435188  -18.000000   680.000000  67.860001   
2019-09-16  38.000038  67.948936  -43.999985   720.999878  96.000000   
2019-03-20  83.999962  56.084835  -84.999992   546.000000   3.700000   
2019-03-24  24.000046  16.178318  -33.000027   -20.000038  37.400002   
2019-08-15  63.999958   5.392773  -58.000019   846.000061  12.550000   
2019-03-30  11.000037  35.592297   -7.999984   -90.999985  17.680000   

                 PM2.5        PM10      Data  
DATE                                          
2019-06-04    2.420000    2.820000  Y_Actual  
2019-09-26   10.950000   12.670000  Y_Actual  
2019-05-14   31.750000   41.180000  Y_Actual  
2019-04-18   45.180000   50.160000  Y_Actual  
2019-08-31    8.250000    9.110000  Y_Actual  
2019-06-29    8.320000   10.110000  Y_Actual  
2019-07-28   22.040001   23.080000  Y_Actual  
2019-07-09    4.330000    6.960000  Y_Actual  
2019-09-07   23.180000   23.709997  Y_Actual  
2019-07-17    6.130000    7.800000  Y_Actual  
2019-08-26   27.050001   51.709999  Y_Actual  
2019-06-02   91.839996   93.289993  Y_Actual  
2019-07-31    5.200000    6.300001  Y_Actual  
2019-07-02   23.000000   24.870001  Y_Actual  
2019-08-10   51.669998   56.199997  Y_Actual  
2019-03-14    1.370000    1.380000  Y_Actual  
2019-09-21   83.139999   84.489998  Y_Actual  
2019-09-14   58.069996   59.570000  Y_Actual  
2019-05-16   10.230000   10.390000  Y_Actual  
2019-09-23   78.370003   79.160004  Y_Actual  
2019-09-16  111.620003  112.300003  Y_Actual  
2019-03-20    4.030000    4.130000  Y_Actual  
2019-03-24   42.400002   46.700001  Y_Actual  
2019-08-15   14.510001   16.059999  Y_Actual  
2019-03-30   20.500000   23.870001  Y_Actual

In [58]:
import pandas as pd
df2=pd.DataFrame(y_test_pred,index=dates,columns=['NO2','O3','NO','CO','PM1','PM2.5','PM10'])
df2.index.name="DATE"
print("Predicted Values:")
df2

Predicted Values:


NO2       O3         NO          CO        PM1      PM2.5  \
DATE                                                                          
2019-06-04  47.849255  11.8641 -80.664482  490.139801   2.968223   3.418961   
2019-09-26  31.278259  11.8641  -5.546434  341.499512  10.155688  10.203463   
2019-05-14  51.198467  11.8641 -25.094217 -132.613449  13.112359  15.961463   
2019-04-18  49.207836  11.8641 -44.744858  681.868164  29.937065  35.181923   
2019-08-31  33.853252  11.8641  -5.958789  -82.559654   6.641768   8.177238   
...               ...      ...        ...         ...        ...        ...   
2019-03-29  34.035519  11.8641   4.500061   -2.882016   6.573976   8.000960   
2019-06-29  50.424248  11.8641 -70.336044  446.676208   1.701109   2.388438   
2019-10-02  46.449802  11.8641 -32.155125   42.305916  46.402546  53.961266   
2019-09-15  50.424248  11.8641 -72.692688  788.745911   0.973941  -1.853863   
2019-07-09  31.278259  11.8641 -40.294590  743.140747   3.909797   5.449862   

                 PM10  
DATE                   
2019-06-04   3.777236  
2019-09-26  13.379510  
2019-05-14  18.418491  
2019-04-18  34.957455  
2019-08-31  11.174068  
...               ...  
2019-03-29   9.871785  
2019-06-29   3.165210  
2019-10-02  59.906017  
2019-09-15   2.013185  
2019-07-09   9.473277  

[432571 rows x 7 columns]

In [59]:
arr=["Y_Predicted"]*25
temp_df2=df2.head(25)
temp_df2['Data']=arr
temp_df2.to_excel("xgboost_y_test_pred.xlsx")
temp_df2

/tmp/ipykernel_2698415/3694748081.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df2['Data']=arr


NO2       O3         NO          CO         PM1       PM2.5  \
DATE                                                                            
2019-06-04  47.849255  11.8641 -80.664482  490.139801    2.968223    3.418961   
2019-09-26  31.278259  11.8641  -5.546434  341.499512   10.155688   10.203463   
2019-05-14  51.198467  11.8641 -25.094217 -132.613449   13.112359   15.961463   
2019-04-18  49.207836  11.8641 -44.744858  681.868164   29.937065   35.181923   
2019-08-31  33.853252  11.8641  -5.958789  -82.559654    6.641768    8.177238   
2019-06-29  33.853252  11.8641  -0.245414   53.225464    5.441239    6.818439   
2019-07-28  46.449802  11.8641 -25.094217   13.388914   20.047733   25.953154   
2019-07-09  53.529594  11.8641 -83.021126  597.863037    2.480992    3.223890   
2019-09-07  44.022236  11.8641 -44.744858  554.178040   20.883434   24.786587   
2019-07-17  31.278259  11.8641 -10.514546  188.213699    5.942058    7.168122   
2019-08-26  46.449802  11.8641 -44.744858  751.717529   22.220039   25.481670   
2019-06-02  41.326187  11.8641 -10.574729  294.465881  116.633446  116.314445   
2019-07-31  50.424248  11.8641 -79.671173  591.712830    6.533908    7.976984   
2019-07-02  41.326187  11.8641 -32.155125 -153.232727   21.627821   24.917156   
2019-08-10  46.449802  11.8641 -49.695412  665.864929   41.138805   50.126495   
2019-03-14  53.181507  11.8641 -72.692688  576.768372    2.633922    3.368436   
2019-09-21  33.853252  11.8641  -5.958789  213.068619   69.390625   74.694786   
2019-09-14  44.540039  11.8641 -97.553688  658.555603   53.490242   60.020447   
2019-05-16  31.278259  11.8641 -95.460068  102.390938    6.968796    8.411176   
2019-09-23  31.278259  11.8641 -76.030304  454.026001   67.837219   79.027451   
2019-09-16  46.449802  11.8641 -25.094217  809.930542   82.519211   98.026215   
2019-03-20  53.181507  11.8641 -67.946678  461.637115    3.506564    4.345070   
2019-03-24  49.207836  11.8641 -28.033913  -11.453885   44.020336   47.540138   
2019-08-15  46.449802  11.8641 -44.744858  753.263550   19.144459   22.224684   
2019-03-30  46.780273  11.8641 -25.094217  -69.518707   20.866772   22.700638   

                  PM10         Data  
DATE                                 
2019-06-04    3.777236  Y_Predicted  
2019-09-26   13.379510  Y_Predicted  
2019-05-14   18.418491  Y_Predicted  
2019-04-18   34.957455  Y_Predicted  
2019-08-31   11.174068  Y_Predicted  
2019-06-29    9.191825  Y_Predicted  
2019-07-28   27.592951  Y_Predicted  
2019-07-09    3.449823  Y_Predicted  
2019-09-07   25.654226  Y_Predicted  
2019-07-17   10.111341  Y_Predicted  
2019-08-26   27.835123  Y_Predicted  
2019-06-02  124.507812  Y_Predicted  
2019-07-31    9.212357  Y_Predicted  
2019-07-02   29.767757  Y_Predicted  
2019-08-10   58.979370  Y_Predicted  
2019-03-14    3.184865  Y_Predicted  
2019-09-21   76.302597  Y_Predicted  
2019-09-14   67.460785  Y_Predicted  
2019-05-16    8.570260  Y_Predicted  
2019-09-23   79.867638  Y_Predicted  
2019-09-16  100.800011  Y_Predicted  
2019-03-20    5.713189  Y_Predicted  
2019-03-24   50.579697  Y_Predicted  
2019-08-15   23.900614  Y_Predicted  
2019-03-30   28.107666  Y_Predicted

In [ ]:
#Completed