# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import os.path as op
import pickle

# Data Fetching

In [2]:
A1=np.empty((0,5),dtype='float32')
U1=np.empty((0,7),dtype='float32')
node=['150','149','147','144','142','140','136','61']
mon=['Apr','Mar','Aug','Jun','Jul','Sep','May','Oct']
for j in node:
  for i in mon:
    inp= pd.read_csv('../../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[1,2,3,15,16],low_memory=False)
    out= pd.read_csv('../../data_gkv/AT510_Node_'+str(j)+'_'+str(i)+'19_OutputFile.csv',usecols=[5,6,7,8,17,18,19],low_memory=False)
    
    inp=np.array(inp,dtype='float32')
    out=np.array(out,dtype='float32')
    
    A1=np.append(A1, inp, axis=0)
    U1=np.append(U1, out, axis=0)

print(A1)
print(U1)


[[1.50000e+02 1.90401e+05 7.25000e+02 2.75500e+01 8.03900e+01]
 [1.50000e+02 1.90401e+05 8.25000e+02 2.75600e+01 8.03300e+01]
 [1.50000e+02 1.90401e+05 9.25000e+02 2.75800e+01 8.02400e+01]
 ...
 [6.10000e+01 1.91020e+05 1.94532e+05 2.93700e+01 7.52100e+01]
 [6.10000e+01 1.91020e+05 1.94632e+05 2.93500e+01 7.52700e+01]
 [6.10000e+01 1.91020e+05 1.94732e+05 2.93400e+01 7.53000e+01]]
[[ 28.     3.   -52.   ...  16.97  19.63  20.06]
 [ 28.    15.   -53.   ...  16.63  19.57  23.06]
 [ 31.    16.   -55.   ...  17.24  19.98  20.24]
 ...
 [ 76.    12.   -76.   ...   3.47   3.95   4.35]
 [ 75.    13.   -76.   ...   3.88   4.33   4.42]
 [ 76.    12.   -75.   ...   3.46   4.07   4.28]]


# A fast algorithm for Independent Component Analysis Decomposition

In [3]:
from sklearn.decomposition import FastICA
import warnings
scaler_obj1=FastICA()
scaler_obj2=FastICA()
X1=scaler_obj1.fit_transform(A1)
Y1=scaler_obj2.fit_transform(U1)

warnings.filterwarnings(action='ignore', category=UserWarning)

# Parameter Tuning

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import RandomizedSearchCV

def hyperParameterTuning(X_train, y_train):
    param_tuning = {
        'learning_rate': [0.01, 0.1],
        'max_depth': [7,8,10,],
        'min_child_weight': [1, 3, 5],
        'subsample': [0.5, 0.7],
        'n_estimators' : [80,90,100,200,400,1000],
        'objective': ['reg:squarederror','count:poisson']
    }

    xgb_model = XGBRegressor(tree_method='gpu_hist', gpu_id=0)

    gsearch = RandomizedSearchCV(estimator = xgb_model, param_distributions = param_tuning, n_iter = 5, cv = 2, verbose=2, random_state=0, n_jobs = -1)

    
    grid_result = MultiOutputRegressor(gsearch).fit(x_train, y_train)

    return grid_result.estimators_[0].best_params_

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.25,random_state=0)

params=hyperParameterTuning(x_train,y_train)
params

# Model

In [4]:
# Splitting Data into training and testing dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.25,random_state=42)

from sklearn.multioutput import MultiOutputRegressor
from xgboost import XGBRegressor

#creating object of sgboostregressor
model1=MultiOutputRegressor(XGBRegressor(tree_method='gpu_hist', gpu_id=0,max_depth=8,cosample_bytree=.5,learning_rate=.1,min_child_weight=3,
                   n_estimators=200,subsample=.7))

#training the model
model_fit1=model1.fit(x_train, y_train)
print("Model training is Done!!")

#saving as file
filename1 = 'xgboost.sav'
pickle.dump(model_fit1, open(filename1, 'wb'))

[14:07:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576: 
Parameters: { "cosample_bytree" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[14:07:57] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576: 
Parameters: { "cosample_bytree" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[14:08:05] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576: 
Parameters: { "cosample_bytree" } might not be use

# Error Analysis

In [5]:
from sklearn.metrics import r2_score
from sklearn import metrics
train_sizes=['NO2','O3','NO','CO','PM1','PM2.5','PM10']

#finding out the r2 score
y_train_pred1=model1.predict(x_train)
r2_train1=r2_score(y_train,y_train_pred1,multioutput='variance_weighted')

y_test_pred1=model1.predict(x_test)
r2_test1=r2_score(y_test,y_test_pred1,multioutput='variance_weighted')

print('r2 score on train data '+str(r2_train1))
print('r2 score on test data '+ str(r2_test1))

xgboost_mae=metrics.mean_absolute_error(y_test, y_test_pred1)
xgboost_mse=metrics.mean_squared_error(y_test, y_test_pred1)
xgboost_rmse=np.sqrt(xgboost_mse)
print('Mean Absolute Error:',xgboost_mae)
print('Mean Squared Error:',xgboost_mse )
print('Root Mean Squared Error:',xgboost_rmse)
print(' \n')

r2 score on train data 0.6324529971892136
r2 score on test data 0.14156921414635998
Mean Absolute Error: 0.00012905022753085157
Mean Squared Error: 1.915377379008494e-07
Root Mean Squared Error: 0.00043765024608795707
 



# Prediction of particles

In [6]:
import pickle
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.25,random_state=42)
loaded_model_fit7 = pickle.load(open("xgboost.sav", 'rb'))
y_test_pred=loaded_model_fit7.predict(x_test)
print("Predicted :\n",y_test_pred)
print("\n")
r2_test=r2_score(y_test,y_test_pred,multioutput='variance_weighted')
print("R2 Score : ",r2_test)

Predicted :
 [[-5.7199410e-05  2.7625161e-05 -1.2138559e-06 ... -2.4311650e-05
  -1.1513624e-04  3.1531112e-05]
 [ 1.4481033e-04  5.3320367e-05 -5.2308377e-07 ... -5.7751557e-05
  -9.4005292e-05 -2.6711590e-05]
 [ 8.8566187e-05  5.0223760e-05 -9.1260392e-07 ... -2.7807588e-05
   5.3635649e-06 -3.0126119e-05]
 ...
 [-1.9085755e-06 -4.1146604e-06  6.4858995e-07 ...  1.9320785e-05
  -4.2327512e-05 -9.2818900e-06]
 [-6.1971041e-05  3.8131759e-05  8.3124638e-07 ... -2.1323616e-05
  -1.3361390e-04  2.2658489e-05]
 [ 1.8561255e-04  3.4789430e-06 -1.3847192e-06 ... -3.3684340e-05
   6.7150089e-05  1.2614171e-05]]


R2 Score :  0.14156921414635998


In [7]:
x_test=scaler_obj1.inverse_transform(x_test)
y_test_pred=scaler_obj2.inverse_transform(y_test_pred)
y_test=scaler_obj2.inverse_transform(y_test)
pd.DataFrame(y_test_pred)

0            1           2           3          4          5  \
0        86.498520   632.667113  -73.147263  717.784748   4.273713   4.927039   
1      -128.010839 -2035.074324   11.818634  385.640413  15.764338  17.754541   
2       328.161695   573.881641 -103.818482  226.303236  22.111039  25.590532   
3        82.322598  1402.864927  -67.111745  672.756982  13.190700  15.621035   
4        40.507800 -2762.034270  -50.703266  174.752272  22.709509  26.048118   
...            ...          ...         ...         ...        ...        ...   
432566 -216.710036 -2691.250336   81.847611   40.110101   6.013289   6.474002   
432567  130.376889   290.912553  -95.292659  585.990310   2.534069   2.903450   
432568 -144.284571 -4251.106144  -12.592735  374.096489  31.909968  37.270690   
432569  134.803318    58.695636  -97.944594  571.105188   1.938992   2.155027   
432570 -144.782987  -494.545688  -26.641459  829.707912  11.296411  13.007497   

                6  
0        5.721196  
1       20.287594  
2       28.656824  
3       19.290451  
4       28.652838  
...           ...  
432566   8.020694  
432567   3.609272  
432568  39.692084  
432569   2.721193  
432570  16.927361  

[432571 rows x 7 columns]

In [8]:
import datetime
from datetime import datetime
temp_arr=x_test[0:,1]
dates=list()
for i in range(0,len(temp_arr)):
    datetime_str=str(int(temp_arr[i]))
    datetime_str=datetime_str[0:6]
    if(datetime_str[4:6]=="00"):
        datetime_str=datetime_str[0:4]+'1'
    datetime_obj = datetime.strptime(datetime_str,"%y%m%d")
    dates.append(str(datetime_obj.date()))


In [9]:
import pandas as pd
df1=pd.DataFrame(y_test,index=dates,columns=['NO2','O3','NO','CO','PM1','PM2.5','PM10'])
df1.index.name="DATE"
print("Actual Values:")
df1

Actual Values:


NO2     O3    NO           CO        PM1      PM2.5       PM10
DATE                                                                       
2019-06-03  82.0   36.0 -79.0   706.000000   2.000000   2.420000   2.820000
2019-09-25  19.0   50.0  -8.0   478.000000  10.170000  10.950000  12.670000
2019-05-13  58.0   38.0 -34.0  -107.000031  27.400000  31.750000  41.180000
2019-04-18  83.0    5.0 -27.0  1579.999969  39.410000  45.180000  50.160000
2019-08-30   5.0   54.0  -4.0  -170.000031   6.900000   8.250000   9.110000
...          ...    ...   ...          ...        ...        ...        ...
2019-03-28  -3.0  104.0  64.0    29.000000   7.130000   7.980000   8.190000
2019-06-29  77.0   40.0 -81.0   413.000000   1.940001   2.610001   4.120001
2019-10-02  21.0    3.0 -48.0    -3.000000  52.910002  61.519999  67.230001
2019-09-14  71.0   40.0 -87.0   608.000000   7.600000   8.020000   8.020000
2019-07-09  -9.0   -5.0 -16.0   592.000000   3.500000   4.219999   4.389999

[432571 rows x 7 columns]

In [10]:
arr=["Y_Actual"]*25
temp_df1=df1.head(25)
temp_df1['Data']=arr
temp_df1.to_excel("xgboost_y_test.xlsx")
temp_df1

C:\Users\utkar\AppData\Local\Temp/ipykernel_4388/2545994415.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df1['Data']=arr


NO2    O3     NO           CO        PM1       PM2.5        PM10  \
DATE                                                                            
2019-06-03  82.0  36.0  -79.0   706.000000   2.000000    2.420000    2.820000   
2019-09-25  19.0  50.0   -8.0   478.000000  10.170000   10.950000   12.670000   
2019-05-13  58.0  38.0  -34.0  -107.000031  27.400000   31.750000   41.180000   
2019-04-18  83.0   5.0  -27.0  1579.999969  39.410000   45.180000   50.160000   
2019-08-30   5.0  54.0   -4.0  -170.000031   6.900000    8.250000    9.110000   
2019-06-29  10.0  34.0   35.0    52.000000   6.889999    8.320000   10.110000   
2019-07-28  24.0   6.0  -38.0   -69.000000  18.180000   22.040001   23.080000   
2019-07-09  72.0  12.0  -93.0   649.000000   3.120000    4.330000    6.960001   
2019-09-06  52.0  66.0  -73.0   244.000000  20.639999   23.180000   23.709999   
2019-07-16   8.0  51.0   -3.0   206.000000   4.889999    6.130000    7.800000   
2019-08-26  67.0   5.0  -34.0   904.000000  24.240000   27.049999   51.709999   
2019-06-02  43.0  -9.0    2.0   303.000000  77.669996   91.839998   93.289999   
2019-07-30  82.0  37.0  -97.0   615.000000   4.780001    5.200000    6.300001   
2019-07-02  19.0  -5.0  -43.0  -154.000031  19.459999   23.000000   24.870001   
2019-08-10  53.0  -3.0  -55.0   832.000000  41.430000   51.669998   56.200003   
2019-03-14  74.0  29.0 -100.0   479.000000   1.240000    1.370001    1.379999   
2019-09-20   4.0  87.0   -7.0   253.000000  75.269995   83.140001   84.489996   
2019-09-13  26.0  20.0 -142.0   321.000000  48.099998   58.070002   59.569998   
2019-05-15  21.0  60.0 -151.0    26.000000   8.720000   10.230000   10.390000   
2019-09-22  22.0  33.0  -18.0   680.000000  67.859999   78.370005   79.160002   
2019-09-15  38.0  68.0  -44.0   721.000000  95.999998  111.620005  112.300001   
2019-03-19  84.0  56.0  -85.0   546.000000   3.700000    4.030001    4.129999   
2019-03-24  24.0  16.0  -33.0   -20.000000  37.400002   42.400002   46.700001   
2019-08-15  64.0   5.0  -58.0   846.000000  12.550000   14.510000   16.059999   
2019-03-29  11.0  36.0   -8.0   -91.000031  17.680000   20.500000   23.870001   

                Data  
DATE                  
2019-06-03  Y_Actual  
2019-09-25  Y_Actual  
2019-05-13  Y_Actual  
2019-04-18  Y_Actual  
2019-08-30  Y_Actual  
2019-06-29  Y_Actual  
2019-07-28  Y_Actual  
2019-07-09  Y_Actual  
2019-09-06  Y_Actual  
2019-07-16  Y_Actual  
2019-08-26  Y_Actual  
2019-06-02  Y_Actual  
2019-07-30  Y_Actual  
2019-07-02  Y_Actual  
2019-08-10  Y_Actual  
2019-03-14  Y_Actual  
2019-09-20  Y_Actual  
2019-09-13  Y_Actual  
2019-05-15  Y_Actual  
2019-09-22  Y_Actual  
2019-09-15  Y_Actual  
2019-03-19  Y_Actual  
2019-03-24  Y_Actual  
2019-08-15  Y_Actual  
2019-03-29  Y_Actual

In [11]:
import pandas as pd
df2=pd.DataFrame(y_test_pred,index=dates,columns=['NO2','O3','NO','CO','PM1','PM2.5','PM10'])
df2.index.name="DATE"
print("Predicted Values:")
df2

Predicted Values:


NO2           O3          NO          CO        PM1  \
DATE                                                                     
2019-06-03   86.498520   632.667113  -73.147263  717.784748   4.273713   
2019-09-25 -128.010839 -2035.074324   11.818634  385.640413  15.764338   
2019-05-13  328.161695   573.881641 -103.818482  226.303236  22.111039   
2019-04-18   82.322598  1402.864927  -67.111745  672.756982  13.190700   
2019-08-30   40.507800 -2762.034270  -50.703266  174.752272  22.709509   
...                ...          ...         ...         ...        ...   
2019-03-28 -216.710036 -2691.250336   81.847611   40.110101   6.013289   
2019-06-29  130.376889   290.912553  -95.292659  585.990310   2.534069   
2019-10-02 -144.284571 -4251.106144  -12.592735  374.096489  31.909968   
2019-09-14  134.803318    58.695636  -97.944594  571.105188   1.938992   
2019-07-09 -144.782987  -494.545688  -26.641459  829.707912  11.296411   

                PM2.5       PM10  
DATE                              
2019-06-03   4.927039   5.721196  
2019-09-25  17.754541  20.287594  
2019-05-13  25.590532  28.656824  
2019-04-18  15.621035  19.290451  
2019-08-30  26.048118  28.652838  
...               ...        ...  
2019-03-28   6.474002   8.020694  
2019-06-29   2.903450   3.609272  
2019-10-02  37.270690  39.692084  
2019-09-14   2.155027   2.721193  
2019-07-09  13.007497  16.927361  

[432571 rows x 7 columns]

In [12]:
arr=["Y_Predicted"]*25
temp_df2=df2.head(25)
temp_df2['Data']=arr
temp_df2.to_excel("xgboost_y_test_pred.xlsx")
temp_df2

C:\Users\utkar\AppData\Local\Temp/ipykernel_4388/3694748081.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df2['Data']=arr


NO2            O3          NO          CO        PM1  \
DATE                                                                       
2019-06-03    86.498520    632.667113  -73.147263  717.784748   4.273713   
2019-09-25  -128.010839  -2035.074324   11.818634  385.640413  15.764338   
2019-05-13   328.161695    573.881641 -103.818482  226.303236  22.111039   
2019-04-18    82.322598   1402.864927  -67.111745  672.756982  13.190700   
2019-08-30    40.507800  -2762.034270  -50.703266  174.752272  22.709509   
2019-06-29     1.133919  -1158.751586    5.253900   97.012636   7.041149   
2019-07-28    -7.695644  -1084.773397  -20.686683  259.247259  25.357452   
2019-07-09    77.614479    208.289623  -84.130059  695.450443   4.464519   
2019-09-06   -41.149735  -2698.158378  -62.809816  502.248203  23.290084   
2019-07-16   -66.339473  -1199.920294    0.942039  238.790428  10.733668   
2019-08-26   -50.150946  -4585.787826 -114.235734  807.684485  33.357239   
2019-06-02  1829.439146  20800.067050 -246.257060 -655.048256  50.394225   
2019-07-30    92.770306    -31.876622  -84.335191  608.363914   3.292046   
2019-07-02    61.012433  -1364.673566  -28.574660  170.564655  49.692235   
2019-08-10    -6.970917  -1962.544143 -107.540927  718.276629  32.660286   
2019-03-14     0.974612    449.313061  -69.717464  728.968990   4.436723   
2019-09-20  -177.102255  -3582.692128   27.317904  180.646886  23.828402   
2019-09-13   366.508328  -6329.431437 -241.743706  296.233623  22.852524   
2019-05-15   226.596478     93.045481  -55.603697   37.257701   8.439060   
2019-09-22    -0.433993  -2244.943068  -21.576501  101.261873  18.833156   
2019-09-15   -65.946299  -4930.388096  -63.206212  408.348577  36.269529   
2019-03-19   134.818138   1266.636416  -68.194082  599.692535   2.551152   
2019-03-24   125.259041  -1094.582157  -52.404060  203.334693  34.068942   
2019-08-15  -247.338363  -5480.701091  -19.445735  649.682791  19.767431   
2019-03-29   -57.771405   -912.588210   11.379880   93.570288   9.140088   

                PM2.5       PM10         Data  
DATE                                           
2019-06-03   4.927039   5.721196  Y_Predicted  
2019-09-25  17.754541  20.287594  Y_Predicted  
2019-05-13  25.590532  28.656824  Y_Predicted  
2019-04-18  15.621035  19.290451  Y_Predicted  
2019-08-30  26.048118  28.652838  Y_Predicted  
2019-06-29   7.973965  10.246741  Y_Predicted  
2019-07-28  29.688782  31.634597  Y_Predicted  
2019-07-09   5.152682   5.809915  Y_Predicted  
2019-09-06  27.191585  30.792031  Y_Predicted  
2019-07-16  12.177146  14.912990  Y_Predicted  
2019-08-26  38.645288  42.698079  Y_Predicted  
2019-06-02  61.657332  60.580646  Y_Predicted  
2019-07-30   3.739937   4.440597  Y_Predicted  
2019-07-02  58.775063  62.325855  Y_Predicted  
2019-08-10  38.952817  45.031363  Y_Predicted  
2019-03-14   4.955502   5.827382  Y_Predicted  
2019-09-20  27.372485  29.787691  Y_Predicted  
2019-09-13  27.511269  29.366334  Y_Predicted  
2019-05-15  10.290210  11.435914  Y_Predicted  
2019-09-22  21.645647  22.562791  Y_Predicted  
2019-09-15  42.265662  45.020610  Y_Predicted  
2019-03-19   2.863511   3.716902  Y_Predicted  
2019-03-24  39.971171  43.028679  Y_Predicted  
2019-08-15  22.585702  24.356583  Y_Predicted  
2019-03-29  10.404960  12.298731  Y_Predicted

In [13]:
#Completed